<script lang="ts">
    import BlogPostPage from "$src/lib/components/blog/BlogPostPage.svelte";
    import PageLang from "$src/lib/components/PageLang.svelte";
    import { blogPost67 } from "./blog_post";
</script>

<PageLang cs />

<BlogPostPage post={blogPost67}>
<div class="picture-cite">
    <p><img src="/photos/pong/1-XD-8001.jpg" alt="TV hra XD-8001">
    <cite>Obr. 1: TV hra XD-8001 (Foto: Herní archiv)</cite>
</div>    
<p>Herní konzole ve stylu známého Pongu byly fenoménem 70. let nejen na západě, ale zhruba od přelomu 1976-1977 začaly různé jejich verze vznikat i v tehdejším Československu. Říkalo se jim tu zpravidla Televizní tenis, či prostě Televizní hra, a my se nyní v trojdílné minisérii článků zaměříme po technické stránce na jeden unikát mezi nimi.
<p>Podobné herní přístroje se totiž v zásadě dělí na dvě skupiny: Starší verze z diskrétních součástek (nebo jen základní TTL logiky) mívaly jen úplně základní funkcionalitu (jedinou hru s dvěma pálkami a míčkem), přičemž ale byly značně komplikované a drahé. Pokročilejší modely mohly nabídnout řadu vylepšení (více variant hry, mantinely, počítání skóre, zvuk) díky použití specializovaných čipů, kterých ovšem celosvětově nevzniklo mnoho. Dominuje mezi nimi úspěšný AY-3-8500 (1976) britské firmy General Instrument, jehož konkurenty ovšem spočítáme na prstech jedné ruky. Vznikaly pak různé jeho klony či následovníci, byly zde proprietární čipy několika výrobců (např. Atari), pořád ale jde jen o několik málo systémů. V zemích východního bloku se pro tuto generaci televizních her používaly téměř výhradně importované čipy AY-3-8500, případně jejich sovětský klon К145ИК17. To však neplatí pro Teslu Piešťany, která zřejmě jako jediná ve východním bloku (a jedna z mála celosvětově) pro svoji hru XD-8001 vyvinula vlastní specializované čipy, označené MAS601 až 603. Ty se v tuzemsku skutečně prodávaly, jak v hotovém přístroji tak i samostatně, informací o nich je však dodnes k dispozici poměrně málo.
<p>Osobně patřím mezi zvědavce, v nichž strohé údaje z dobových katalogů Tesly budí po léta nezodpovězené otázky. V posledních letech lze ve světě pozorovat určitou vlnu zájmu o historii her v rovině obecné i technické (a dokonce i akademické), vznikají projekty ke zdokumentování či rovnou emulaci různých systémů a čipů, jako již zmíněný <a href="https://nerdstuffbycole.blogspot.com/">AY-3-8500 s následovníky</a>, <a href="http://www.visual6502.org/">dobové mikroprocesory a čipy z herních konzolí či mikropočítačů</a>, někde dokonce vznikají novodobé repliky historicky existujících nebo i jen <a href="https://forums.atariage.com/topic/377991-1090xl-parallelserial-card/">plánovaných</a> zařízení - ať už z důvodů nostalgických, historicky dokumentačních, nebo prostě k nahrazení postupně selhávající staré techniky. I já jsem se v tomto inspiroval, a rozhodl jsem se pro podobné zvědavce, a možná i jako ukázku tuzemské technologie 70. let, trochu poodhalit roušku tajemství kolem zmíněných televizních her z Piešťan.
<p>Ještě zmíním, že tyto články mohly vzniknout jen díky aktivitě spolku <a href="https://hernihistorie.cz/">Herní historie</a>, fotografické dokumentaci čipů kterou pořídil <a href="https://seanriddle.com/decap.html">Sean Riddle</a>, a v neposlední řadě i archivním materiálům a dalším informacím, které zmíněnému spolku poskytl sám autor Piešťanských čipů, ing. Vladimír Áč.
<p>Historie vzniku Piešťanských her se poněkud vymyká zaměření tohoto článku, a je zároveň i předmětem dalšího bádání, nicméně samotné čipy byly vytvořeny již v průběhu roku 1977. Původně neoficiální projekt nakonec vyústil ve výrobu čipů i finálního přístroje, který stejně jako dva předchozí typy navrhoval ing. Ján Hladík. Výroba se ovšem rozběhla až po dlouhých dvou letech, v roce 1979.
<p>Přístroj XD-8001 nabízí čtyři navzájem podobné hry, jak ukazují obrázky známé z dobových katalogů Tesly (obr. 2): Je zde klasický televizní Tenis pro dva hráče, kteří své pálky ovládají pomocí potenciometrů, dále varianta Trénink tenis pro jednoho hráče, který hraje proti stěně. Třetí možností je Fotbal s částečnými mantinely, které na koncích hřiště vymezují branky, a s dvěma pálkami pro každého hráče (brankář a útočník na soupeřově polovině hřiště), tato hra ovšem připomíná spíše hokej, protože míč (či puk) se od mantinelů odráží zpět na hřiště. Poslední hrou je Pelota, která se podobá hře Trénink Tenis - jde opět o hru jednoho hráče proti stěně, tentokrát ovšem bez středové sítě. Hra také průběžně počítá a zobrazuje skóre obou hráčů až do 15 bodů. Tlačítky lze přepínat dvě rychlosti pohybu míče, a také ruční nebo automatické podání.
<div class="picture-cite">
    <p><img src="/photos/pong/2-nakresy-her.jpg" alt="Nákresy her">
    <cite>Obr. 2: Čtyři hry konzole XD-8001 (katalog Tesla)</cite>
</div>
<p>Srovnáme-li hru s nejrozšířenější zahraniční verzí, tedy zmíněným čipem AY-3-8500, může se na první pohled jevit velmi podobná. Při bližším pohledu však najdeme řadu rozdílů. Západní verze má namísto Peloty hru Squash, kde hrají oba hráči na stejné straně hřiště, umí při hře jednoho hráče skrýt druhé skóre, navíc jsou zde ještě dvě hry se světelnou puškou. Naproti tomu XD-8001 vytváří větší rozdíl mezi hrami Tenis a Fotbal. Odrazy míče od hráčů při fotbalu míří vždy ke středu hřiště (z horní poloviny dolů a naopak), při ostatních hrách jsou náhodné, což vytváří moment překvapení. Naproti tomu s AY závisí odraz míče na tom, jakou částí pálky byl odražen (což by při koncepci tuzemské verze nebylo možné realizovat). V obou verzích se může úhel letu míče změnit i pokud pálkou prochází ze zadní strany (kdy se ovšem neodráží). Další rozdíl nastává po gólu, kdy v Piešťanské verzi míč začíná při fotbalu výkopem zhruba ze středu hřiště, a jen v ostatních hrách se servíruje klasicky od základní čáry. Liší se i směr míče, který v případě AY letí znovu stejným směrem, jakým padl gól, zatímco XD-8001 míč posílá zpět od vstřelené branky - v případě fotbalu je to realističtější, zatímco relativně složitou logiku tenisových podání nerespektuje žádný z obou čipů. Automatické podání je vázané na dva odrazy míče od horního či spodního mantinelu, čímž vedle určité prodlevy vzniká i prakticky diagonální výkop z rohu resp. středu hřiště, zatímco u AY míč prostě jen proletí skrz okraje na opačnou stranu obrazovky. Dalším významným rozdílem je funkce středové sítě či čáry, která je v případě AY jen estetická, bez vlivu na pohyb míče, zatímco u nás se při obou variantách tenisu může s určitou pravděpodobností změnit směr míče při průchodu touto sítí. Naproti tomu při fotbalu se i zde jedná jen o středovou čáru, která míč neovlivňuje (Pelota nemá středovou čáru vůbec). Zatímco AY umí změnit rychlost a úhel odrazů míče, a také délku pálek obou hráčů, Piešťanská verze má osazený jen přepínač dvou rychlostí (nutno však podotknout, že i ostatní zmíněné parametry by bylo možno vhodnou úpravou zapojení plynule měnit, případně by bylo možné omezit i rychlost pohybu hráčů). V neposlední řadě v tuzemské verzi nastává skutečný konec hry, kdy se po dosažení 15 bodů zobrazí výsledné skóre na jinak prázdné obrazovce, zatímco u AY-3-8500 v podstatě jen přestanou fungovat pálky a počítání skóre, aniž by se jinak na hře cokoliv změnilo.
<p>Další rozdíly jsou spíše estetické. Nejvíce viditelným rozdílem je asi hra proti stěně směrem doprava (v případě AY je to naopak), a také zobrazení skóre, které se v Piešťanské verzi objevuje jen po vstřelení gólu, po znovuzahájení hry pak s jistým zpožděním zhasíná. V tomto (i v dalších bodech) se hra poněkud podobá verzi publikované dříve v Amatérském Radiu, souvisí to však především s logikou servírování a počítání skóre. Liší se i čáry po okrajích hřiště, které jsou na rozdíl od AY silné a nepřerušované, s typickými přesahy na levé a pravé straně (kde je totiž součástí motivu ještě neviditelná "gólová čára"), jiná je i středová síť (podle verze AY). Zvukové efekty jsou prakticky stejné, jen vstřelené góly AY indikuje pípnutím, zatímco v případě MAS601 se původně asi zamýšlená píšťalka do definitivní verze nedostala. Při čekání na restart hry po gólu je slyšet skákání míče mezi horním a spodním okrajem hřiště, přestože je míč mimo obrazovku.
<p>Zkusme si nyní stručně připomenout princip této generace televizních her. Dnes jsme zvyklí na počítačové systémy, které sestaví prakticky libovolný obraz jako bitmapu v určité části paměti, kterou pak příslušným hardwarem promítnou na obrazovku. Herní konzole 70. let však vzhledem k omezeným technickým možnostem tuto abstrakci zpravidla nepoužívaly a propojovaly princip hry přímo s tvorbou analogového videosignálu. Tehdy běžný analogový televizor kreslil obraz po pixelových řádcích (jako se čte stránka textu), kde světlost jednotlivých míst byla určena v reálném čase napětím vstupního signálu. Přidané impulsy opačné polarity označují začátky jednotlivých řádků a snímků - a to už je vlastně všechno, co jednoduchá konzole potřebovala. Jde tedy jen o černobílý obraz bez prokládaných půlsnímků, zvuku či dalších doplňků. Jednotlivé herní elementy (pálky, míč, mantinely atd.) byly vytvářeny pevně propojenou logikou v podobě vhodně časovaných impulsů, synchronních s vykreslováním obrazu na televizoru. V nejjednodušší verzi k tomu stačilo několik monostabilních klopných obvodů: Jak televizor postupně kreslí obrázek shora dolů, nabíjí se kondenzátor, který podle natočení potenciometru v ovladači dříve nebo později dosáhne k rozhodující napěťové hranici. Tím vznikne impuls, který na obrazovku nakreslí světlý flíček - například pálku. Sloučením impulsů různých prvků hry vzniká přímo hotový videosignál pro televizor, zatímco porovnáním jejich souběhu v čase se zas detekují kolize: Má-li televizor kreslit současně obrázek míče i pálky, je jasné, že jsme se trefili a míč se má odrazit (překlopí se klopný obvod, který řídí směr míče). Takovýto pevně zadrátovaný princip je sice pro funkci hry značně omezující a nepružný, funguje však i s velmi skromnou technikou, bez jakýchkoliv pixelů či bajtů paměti.
<p>Nejstarší konzole Magnavox Odyssey a její klony si díky tomu vystačily se skromným počtem diskrétních tranzistorů, i mnohé pozdější systémy však převzaly tentýž princip. Zásadní změnu u zahraničních výrobců dokonce nepřinesl ani příchod mikroprocesorů, které zpočátku jen nahradily řídící logiku hry, zatímco videosignál nadále vznikal v reálném čase kombinací dílčích signálů jednotlivých komponent hry, více či méně vylepšených. Dělá to tak mikrokontrolérem řízený herní čip MOS7600, a pěkným příkladem je i firma Atari, kde srovnatelný princip od prvního Pongu, přes mikroprocesorem řízenou konzoli Atari 2600, přetrval až do počítačů řady XL/XE v 80. letech (mají ještě i detekci kolizí či snímání polohy potenciometrů a světelné pušky, třebaže přijaly také řadu rysů z větších počítačů). V tuzemsku sice příklad podobného mezistupně mezi televizní hrou a počítačem patrně nemáme, Piešťanské televizní hry však uvedený princip pochopitelně používaly. Byla to v době jejich vzniku obvyklá, a vlastně i jediná použitelná možnost.
<p>Pojďme nyní nahlédnout do vnitřností konzole Tesla XD-8001. Po rozšroubování skříňky se kolegům ze spolku Herní historie ukázala deska osázená dobovými součástkami (obr. 3), s trojicí obvodů MAS601-603. Na dalších obrázcích jsem si desku překreslil a převedl na podrobné schéma, tak jak byla hra v Tesle skutečně vyráběna. Na rozdíl od poměrně známého katalogového zapojení obvodů MAS zde vidíme skutečně celý přístroj, najdeme však i další rozdíly (ty uvádím v závorkách a vrátím se k nim později). Na schématu vidíme stabilizovaný napájecí zdroj -18V, jednoduchý obvod zvuku s malým reproduktorem přímo v přístroji, v dolní části pak ovladače připojené tehdy běžnými konektory DIN a tlačítka pro nastavení hry. Překvapí velmi skromné blokování napájecího napětí jen jediným elektrolytickým kondenzátorem (pro vyšší kmitočty málo účinným a podle číslování možná dokonce přidaným až dodatečně).
<div class="picture-cite">
    <p><img src="/photos/pong/3-deska-XD-8001.jpg" alt="Deska v XD-8001">
    <cite>Obr. 3: Deska v XD-8001 (Foto: Herní archiv)</cite>
</div>
<div class="picture-cite">
    <p><img src="/photos/pong/4-osazovacka-XD8001.png" alt="Rozložení součástek na desce">
    <cite>Obr. 4: Rozložení součástek na desce</cite>
</div>
<div class="picture-cite">
    <p><img src="/photos/pong/5-schema-XD8001.jpg" alt="Schéma XD-8001">
    <cite>Obr. 5: Podrobné schéma XD-8001 napříč vývojovými verzemi</cite>
</div>
<p>Dále schéma odhaluje modulátor pro výstup do televizoru, reálně ukrytý v plechové krabičce. V jednom z dřívějších článků jsem komentoval, jak návody publikované v dobových časopisech tuto část obvodu málo vysvětlují, coby věc při tehdy ještě silné radioamatérské tradici víceméně zřejmou, pokusím se tedy neopakovat tutéž chybu a funkci obvodu trochu objasnit. Analogové televizní vysílání kóduje obrazový signál asi nejjednodušším způsobem, kterým je amplitudová modulace: Vysokofrekvenční signál (alias nosná vlna) mění v závislosti na přenášeném obsahu amplitudu (prakticky tedy napětí). Pravá část obvodu (s tranzistorem zapojeným se společnou bází) je tedy v podstatě oscilátor, který vyrábí onen vysokofrekvenční průběh. Modulaci zajišťuje dioda V16, která sinusovku přivádí do společného bodu s přenášeným videosignálem - zákonitě tam však protlačí jen tu část průběhu, která má nižší napětí než aktuální stav signálu, čímž právě dochází ke kýžené změně amplitudy podle přenášeného obsahu. Kondenzátor C19 pak na výstup propustí jen onu měnící se vysokofrekvenční část, která u takto jednoduchého obvodu nebude nijak zvlášť kvalitní (pěkná sinusovka odříznutím části průběhu nevzniká), ale televizor tomu rozumět bude a všechny případné hříchy zůstanou ukryty v oné plechové krabičce a stíněném kablíku. Velmi podobné obvody najdeme ostatně ve většině dobových návodů na televizní hry (v případě doporučeného zapojení západního AY-3-8500 ovšem s alibistickou poznámkou, že zapojení slouží pouze ke zkoušení v laboratoři).
<p>Výstupní kablík je osazen poměrně nezvykle provedenou sestavou dvou různých konektorů, protože v tehdejší době přicházely teprve na trh první televizory s koaxiálním konektorem 75Ω pro anténu, zatímco starší přístroje ještě používaly ploché symetrické konektory 300Ω. Redukce určená k připojení starších kabelů k novějším televizorům je zde použita vlastně naopak, jako koaxiální konektor a zároveň odbočka krátkým kablíkem do starší ploché verze.
<p>Jádrem vlastní hry je obvod MAS601, řízený hodinovým kmitočtem 875kHz přivedeným z MAS603 na vstup T. MAS601 vytváří řádkové i snímkové synchronizační impulsy (výstupy SR a SO), a dává dohromady kompletní obraz a zvuk hry (výstupy M a ZV). Sám ovšem digitálně (pomocí různých čítačů) generuje pouze nepohyblivé obrazce, tedy mantinely, středovou síť a skóre. Na tvorbě pohyblivých částí hry spolupracují zbylé dva obvody, které na rozdíl od MAS601 používají analogový princip obvyklý u starších konzolí. MAS603 řeší obě pálky, jejichž poloha je řízena napětím z ovladačů na vstupech IL/IP. Podle jeho velikosti je v každém snímku pomocí kondenzátorů na pinech CL/CP a RHL/RHP vytvořen v potřebném odstupu od snímkového synchronizačního pulsu (vstupy SO1/SO2) impuls na výstupy LH/PH. Ten je pak přiveden do MAS601, kde omezuje zobrazenou pálku ve svislém směru.
<p>Obvod MAS602 se stará o polohu i zobrazení míče. Směr pohybu je řízen výstupy HPL/VPL z MAS601, jejichž signál (po omezení velikosti vlivem pinů OBH/OBV a nastavitelnými odpory) zvolna nabíjí nebo vybíjí kondenzátor mezi piny IIH/OIH resp. IIV/OIV - jde v podstatě o analogové integrátory, jejichž výstupní napětí pak řídí polohu zobrazeného míče stejně, jako v případě MAS603. Obě složky (horizontální i vertikální) jsou v případě míče sloučeny do jediného výstupu L (označení vychází ze slovenského slova "lopta"), který je prakticky hotovým videosignálem míče. Přidán je však ještě druhý, neviditelný míč, v době zatemnění na začátku obrazového řádku, který slouží obvodu MAS601 k bezpečnému udržení míče na hřišti po gólu, kdy se viditelný míč nezobrazuje. Výstup SYN slučuje pro televizor oba synchronizační impulsy, které vzhledem k odlišné napěťové úrovni nemohou být do videosignálu přimíchány přímo v MAS601.
<p>Průběh hry je dále řízen vstupy A/B/N (výběr hry a nulování skóre), podání po gólu pak poměrně netypickým vstupem S - ten při úrovni -18V drží hru zastavenou, zatímco při úrovni země vpustí míč do hry - to se provádí tlačítkem na ovladači, které je připojeno přes derivační článek, omezující i delší stisk na krátký impuls. Pokud je ovšem vstup S (nezvykle zapojeným spínačem) odpojen, převezme řízení automatika, připojená k tomuto vstupu z vnitřku MAS601 přes odpor, a míč je pak vpuštěn do hry po dvou odrazech od horního/spodního okraje hřiště.
<p>Každý projekt pochopitelně při svém vzniku prochází řadou změn, jaké se nevyhnuly ani hře XD-8001. Různé verze tištěných materiálů ovšem nevznikaly v tomtéž okamžiku, takže se stalo, že zapojení uvedené dle dobové zvyklosti v uživatelském návodu se úplně neshoduje s verzí otištěnou v katalogu součástek, a místy ani s reálně vyráběnými přístroji. Poskytuje nám to zajímavý pohled na vznik celého zařízení a odhaluje, které jeho části se měnily. Drobnější odchylky jsem se snažil v překresleném schématu zachytit pomocí různých druhů závorek, jsou zde ovšem i větší změny, které si můžeme nejlépe ilustrovat na obvodu pro nulování hry do výchozího stavu.
<p>V levé horní části obrázku 6 vidíme ještě poměrně jednoduchou verzi, jaká byla přiložena k vývojové dokumentaci samotných čipů MAS60x. Nulovací tlačítko zde jedním kontaktem maže skóre, druhým po dobu stisku jen posouvá míč směrem vpravo, nejspíš aby se při prvním zapnutí bezpečně dostal z okraje na hřiště. Konkrétnější výchozí poloha míče zde nebyla vůbec řešena, přičemž ale obvod MAS601 v rané verzi sám blokoval nežádoucí góly v začátku hry, až do prvního průchodu míče přes středovou čáru. Odlišné hodnoty dalších součástek naznačují o něco rychlejší pohyb míče a zvláštní je i zmenšené napětí na vstupech pro výběr hry. Tato verze také nepočítala s ručním podáním pomocí tlačítka v ovladači (mimo záběr obrázku).
<div class="picture-cite">
    <p><img src="/photos/pong/6-srovnani-start-hry.png" alt="Srovnání obvodů začátku hry">
    <cite>Obr. 6: Srovnání obvodů začátku hry</cite>
</div>
<p>Verze otištěná v katalogu součástek (vpravo nahoře) již nepočítá s počáteční necitlivostí hry vůči nežádoucím gólům, která byla zřejmě mezitím zrušena. Dostatečné trvání nulovacího signálu je zde zajištěno dodatečným kondenzátorem, zvolna nabíjeným přes pull-up vestavěný v MAS601. Signál rozvětvený přes diody také zavírá (tentokrát již oba) integrátory polohy míče, jejichž kondenzátory jsou navíc přes další diody nabíjeny na předem určené napětí z pomocného zdroje, takže pohyb míče vždy začne zhruba ze středu hřiště. To je uživatelsky hezčí, a také bezpečnější zahájení hry.
<p>Nahlédneme-li do návodu k použití XD-8001 (vlevo dole), vidíme důraznější působení na integrátory, a také zřetelně větší opatrnost v zacházení se vstupy obvodu MAS601, kde přibyly sériové odpory (připomínající spíše styl zacházení s bipolárními obvody, u obvodů MOS diskutabilní), tuto opatrnost prozrazuje i použití tehdy relativně drahých soklů. Druhý kondenzátor také prodlužuje zadávání výchozí polohy míče, která se nyní nastavuje trimrem - to bylo sice vytištěno v návodu, vyrobené desky s plošnými spoji však ještě počítaly na místě trimru jen se sériovým odporem, a také přidaný kondenzátor odlišným typem a vysokým číslem vypadá, jako kdyby na desku původně nepatřil. Objevily se také spínače pro volbu rychlosti míče. I pak ještě došlo k dalším změnám, protože ve skutečném přístroji (vpravo dole) je trimr výchozí polohy míče montovaný mimo původně zamýšlený obrazec desky již tak, že vůbec nepoužívá pomocný zdroj -5V. Zmenšily se i poněkud přestřelené sériové odpory ve vstupech pro volbu hry, a rychlejší pohyb míče byl v průběhu výroby poněkud zpomalen zvětšením dvou odporů.
<p>Další změny bychom našli v sortimentu seřizovacích trimrů a jiných drobnostech, nebo v napájecím zdroji, který byl v nejstarší verzi výrazně odlišný, a vzhledem k poněkud předimenzovanému výstupnímu napětí transformátoru patrně také zápasil s přehříváním - na desce najdeme dva omezovací sériové odpory, z nichž jeden byl montovaný dodatečně, mimo zamýšlený obrazec desky. Sehnat v tehdejší době vyhovující transformátor ovšem asi nebylo nic snadného. Stejně tak se pro přístroj nepodařilo zajistit ani vlastní skříňku, takže byl nakonec navržen do krabičky převzaté z výroby stolních kalkulaček v Tesle Bratislava, pouzdra ovladačů pocházejí z dálkového ovládání hraček, a například hotové cívky nebyly tehdy k dispozici vlastně vůbec, takže v dokumentaci najdeme namísto hodnot indukčnosti spíše návody na jejich ruční výrobu, což bylo tehdy obvyklé.
<p>Tolik tedy krátký pohled na proměny přístroje, které zanechaly svůj otisk v dobové dokumentaci. Nebyl to ve své době vůbec přístroj špatný, je jen škoda, že podobně jako řada dalších československých výrobků přišel se zpožděním několika let za světovým trendem, a prodával se za tehdy nepříjemně vysokou cenu (1610 Kčs).
<p>Závěrem článku přiznávám, že zbývá ještě řada dalších otázek: Proč to rozdělení na 3 obvody? Proč napětí -18V? Proč je půlka hry v podstatě analogová? Jak vlastně logika hry funguje? Tyto a další otázky si nechám na další dva články, v nichž se pokusím ponořit ještě hlouběji - přímo do vnitřní struktury integrovaných obvodů MAS601-603.

<h4>Zdroje:</h4>
<ul><li>Fotodokumentace XD-8001 (Herní archiv)
<li><a href="http://www.litildivil.cz/sbirka/ruzne/TV_hra_tesla.htm">Sken plošného spoje</a>
<li>Sada integrovaných obvodů ke konstrukci televizních her MAS601, MAS602, MAS603 (Technické zprávy, Tesla Rožnov, 1979)
<li>Televízna hra XD 8001 - návod na obsluhu (Tesla Rožnov, n.p., závod Piešťany, pravděpodobně 1979)
<li>Ing. Vladimír Áč: Rozhovor pro spolek Herní historie (2025)
<li>Ing. Vladimír Áč: Technická dokumentace MAS600/601-603 (nepublikovaná pracovní verze, asi 1977-1978)
<li>Katalogový list AY-3-8500 (General Instrument)
<li><a href="https://www.pong-story.com/gi.htm">Pong Story</a>
<li><a href="https://www.youtube.com/watch?v=80nm31Uwf0g">Videozáznam hry</a>
</ul>

<h4>Zdroje obrázků:</h4>
<ul><li>1. <a href="https://inventory.herniarchiv.cz/file/details/?id=12167">Obrázek Tesla XD 8001 od Herní archiv</a>
<li>2. Katalog Tesla (stejné obrázky jsou též v Technické zprávě a vývojové dokumentaci)
<li>3. Fotodokumentaci poskytl Herní archiv
<li>4-6. Vlastní kresby (s použitím skenu plošného spoje který najdete <a href="http://www.litildivil.cz/sbirka/ruzne/TV_hra_tesla.htm">zde</a>)
</ul>

</BlogPostPage>