<script lang="ts">
    /* https://docs.google.com/document/d/1jym3l5vMQyDJuwkU3bANHMhsfRxdkE8A/edit */
	import Interview from "$lib/Interview.svelte";
	import Answer from "$lib/interviews/Answer.svelte"
	import Question from "$lib/interviews/Question.svelte";
	import Chapter from "$lib/interviews/Chapter.svelte";

    import { data, ZV, RS, VS } from "./interview";

    let A = Answer;
    let Q = Question;
</script>

<style>
    .c5 {
        font-style: italic;
    }
</style>

<Interview data={data}>
    <div slot="content">

        <Chapter title="Rodinné zázemí a vzdělání">


            <Q speaker={RS}>Dneska je 27. 6. 2024. Rozhovor je s Ing. Zdeňkem Vodákem v Café Standard a je veden Rudolfem Janem Suchým a Vojtěchem Strakou. Než se dostaneme k vaší činnosti v Československé televizi, tak se vás zeptám, odkud vlastně pocházíte, kde jste se narodil a jaké je vaše rodinné zázemí?</Q>
        
            <A speaker={ZV}>Narodil jsem se na Moravě v malém městečku kousek nad Brnem, které se jmenuje Boskovice. Teď v současné době už tam jezdím jenom na hřbitov, ale pořád se mi Boskovice moc líbí. My jsme se s rodinou z Boskovic relativně brzy přestěhovali do Prahy. Tehdy to tedy ještě nebyla Praha, to byl Újezd nad Lesy, teprve později se z toho stala Praha. My jsme si tam koupili rodinný domek a od té doby tam vlastně žiju. Táta byl technik, dělal v Československé televizi, máma byla účetní. Studoval jsem na gymnáziu – obor matematika, fyzika. Ne, že by mě to teda bavilo, ale na druhou stranu musím říct, že oproti češtině a literatuře, mi aspoň matematika a fyzika připadaly jako zcela konkrétní věci se zcela danými pravidly. Doteď mám problémy s tvrdými a měkkými i a podobně. Po gymnáziu jsem šel na ČVUT FEL, Fakultu elektrotechnickou tady v Dejvicích. Nicméně, studoval jsem tam takový dost netypický obor a sice ekonomiku výroby elektrické energie. Tento obor se zabýval tím, jak nejefektivněji postavit elektrárnu. Po absolvování ČVUT jsem tam zůstal tři roky učit jako asistent. Pak jsem vystřídal během šesti let šest zaměstnání, než jsem zjistil, že mít nadřízeného není zrovna to, co se mi líbí. V té době už to naštěstí bylo možné, takže jsem si udělal živnosťák – OSVČ. Jak jsem říkal, tak táta v té době pracoval v Československé televizi. Začal jako technik na záznamech. Tehdy se to samozřejmě ještě nedělalo na digitální kazety nebo na nějaký cloud. Dělalo se to na široký magnetofonový pásky, jednopalcový nebo čtyřpalcový. Později se stal technologem což obnášelo to, že když se točil v Československé televizi nějaký pořad, tak se předtím sešli vlastně všichni, kteří na tom měli dělat – to znamená nějaký zástupce osvětlovačů, zvukařů, záznamů atd. – a byly tam daný požadavky a jakým způsobem se dají realizovat a táta jako technolog to nějakým způsobem usměrňoval, aby si režisér nevymyslel něco, co v té době nebylo technicky možné. A já se teď možná trošinku vrátím. Vrátím se ještě k té době, kdy jsem studoval na ČVUT.</A>
        
            <Q speaker={RS}>Kdy jste se vlastně dostal na ČVUT?</Q>
        
            <A speaker={ZV}>V roce 1985 jsem končil, to znamená že jsem začínal v roce 1981.</A>
        
            <Q speaker={RS}>Jo, super, děkuji.</Q>
        </Chapter>
        <Chapter title="První počítač">
        
        
            <A speaker={ZV}>Tehdy existovaly prodejny Tuzexu, takže jsem si zcela nelegálně vyměnil koruny za bony a koupil jsem si programovatelnou kalkulačku <span class="c7 c3"><a class="c5" href="https://cs.wikipedia.org/wiki/TI-59">Texas Instrument 58</a></span><span class="c3">. Tu mám dodnes. Programovalo se tam ve strojovém kódu. Dalo se tam nacpat relativně málo příkazů a já jsem to využíval hlavně ve škole, k řešení například kvadratických rovnic. Bezproblémová záležitost – naťukaly se tam číslíčka, zmačklo se tlačítko a ono to vyhodilo nějaké číslo, většinou správně. V té době už taky běžel </span><span class="c0 c7"><a class="c5" href="https://www.filmovyprehled.cz/cs/film/397051/jachyme-hod-ho-do-stroje">Jáchyme, hoď ho do stroje!</a></span><span class="c3">, takže jsem si na tom dělal i kondiciogram. Zadal jsem tam datum narození a kolikátého dnes je a ono to vyplivlo, jaký mám intelektuální schopnosti </span><span class="c3">a tak dále.</span><span class="c3"> No a v té době jsem také odebíral </span><span class="c7 c3"><a class="c5" href="https://cs.wikipedia.org/wiki/Praktick%C3%A1_elektronika_%E2%80%93_Amat%C3%A9rsk%C3%A9_r%C3%A1dio">Amatérské rádio</a></span><span class="c3"> kde jsem se dočetl, že nějaký pan Sinclair v Anglii vytvořil už druhou variantu svého počítače, který nazval </span><span class="c7 c3"><a class="c5" href="https://cs.wikipedia.org/wiki/Sinclair_ZX_Spectrum">ZX Spectrum</a></span><span class="c2">. V tom časopise byl obrázek s popisem co to umí a já jsem si říkal „to musím mít! To není co řešit!” Protože my jsme se na ČVUT programování učili, ale jenom okrajově. Tady kousek na Karláku byl sálový počítač a to programování vlastně probíhalo tak, že tam byla místnost, v který byly dálnopisy. Ten program – myslím, že šlo o FORTRAN – se napsal na tom dálnopisu, z toho dálnopisu vylezla páska, ta se zamotala do ruličky, omotala se gumičkou, tam se napsalo jméno a rulička se hodila do koše. A druhý, třetí den tam člověk přišel a v takové skříňce, kde jsem měl vlastní přihrádku, jsem měl potom výpis. Někdy tam samozřejmě byl napsán nějaký error, ale někdy tam ten výpis doopravdy byl. Nicméně to ZX Spectrum jsem dokonce legálně dostal přes nějakého člověka, který pracoval tehdy v Západním Německu. A do teď si pamatuji, že to stálo dvanáct tisíc, což se teď zdá být relativně málo, nicméně v té době to bylo docela dost. Jenom tak pro srovnání – první plat, který jsem měl jako asistent na té vysoké škole, bylo třináct set devadesát korun hrubého měsíčně.</span></A>
        
            <Q speaker={VS}>Používal jste tu kalkulačku vyloženě jenom pro to studium, nebo jste se na ni snažil dělat už nějaké první vaše programy pro vlastní zábavu? Kde jste se učil s tím pracovat?</Q>
        
            <A speaker={ZV}>S programováním jako takovým jsem se právě poprvé setkal až na té vysoké škole. Myslím, že už v prváku jsme měli nějaký předmět programování nebo spíš algoritmování, kde jsme v podstatě udělali vývojový diagram a teprve později jsme to nějakým způsobem přepisovali do toho FORTRANu. A mně se to hrozně zalíbilo. Já mám rád, když něco udělám a ono to funguje tak, jak chci. Už od začátku kdy jsem si dělal různý takový ty sirénky podle Amatérského rádia a tak podobně. A u těch programů to bylo výrazně jednodušší v tom, že jsem tam zkrátka něco napsal a ono to dělalo to, co chci. A když ne, tak jsem to mírně upravil nebo opravil. No a takže jsem si pořídil tu kalkulačku – víc kvůli tomu samotnému programování než škole. Ono do té kalkulačky se dalo narvat maximálně 100-150 kroků. Ale dělal jsem si to spíš pro sebe. A jak říkám, kondiciogram to byl takový základ. A pak jak jsme byli ta ekonomika výroby elektrické energie a neustále jsme hledali nějaké extrémy funkcí přes derivace a tak dále. jsem si právě zkoušel na té kalkulačce programovat.</A>
        
            <Q speaker={VS}>A objevoval jste to jakoby sám? Bylo něco v tom Amatérském rádiu? Nebo jste si pomáhal třeba se spolužáky? </Q>
        
            <A speaker={ZV}>Tohle jsem v podstatě objevoval sám. Je fakt, že jsem měl ale na ČVUT spolužáka, který měl <span class="c3">59</span><span class="c2">ku, kterou jsem mu samozřejmě ohromně záviděl, s kterým jsme si vyměňovali nějaké nápady a jak některé věci udělat a jak jiné zjednodušit. Ono to bohužel nebylo jako teď, kdy já můžu udělat program, který má X megabajtů. U té kalkulačky byla nějaká optimalizace samozřejmě nezbytná, protože jinak jste do ní nic nedostal. Ale jinak že bych někde čerpal, to úplně ne. V té době to nebylo jako teď. Teď když potřebuju zjistit jak něco udělat, tak zkrátka jdu na internet, a tam teda vyjede jednak spousta nesmyslů, ale zároveň se něco sem tam dá použít. Ale tehdy internet nebyl. Amatérské rádio na to nebylo zaměřený a žádný časopis na programování nebyl. Takže jediné, co mi zbývalo, bylo si to vymýšlet sám. </span></A>
        
            <Q speaker={VS}>Také jste zmiňoval, že jste pravděpodobně na začátku vysoké školy sháněl někde tajně bony, což tehdy muselo být docela dost peněz takhle pro studenta. Podpořili vás třeba rodiče? </Q>
        
            <A speaker={ZV}>To jste mě teď fakt zarazil. Muselo to být někdy na začátku vysoké a asi mě museli podpořit rodiče, protože kde bych jinak sebral peníze. Já jsem byl vždycky líný a navíc brigády v té době ani moc nepřicházely v úvahu. Ono potom na té vysoké jako šprt, který měl samé jedničky, jsem měl stipendium. Což bylo relativně dost – snad nějaké čtyři stovky. No a pak začal ten <span class="c0">Videostop</span><span class="c2">, ale do té doby mě rodiče museli podpořit.</span></A>
        
            <Q speaker={VS}>No a pak se dostáváme k tomu ZX Spectru, které už teda muselo být řádově dražší. Tam si vzpomenete jak jste se dostal třeba k tomu kontaktu, který to přivezl? </Q>
        
            <A speaker={ZV}>Zase táta. Vím, že ten kontakt byl nějaký člověk, který dělal v televizi snad dramaturga a služebně dělal i v zahraničí. My jsme ani nevěděli, jak to sem dostat. Takže první, co nás napadlo, bylo požádat nějakého kamioňáka, aby to provezl někde pod sedadlem. No a právě táta se takhle bavil s nějakým tím člověkem v té televizi a ten řekl, že tam normálně lítá a že se to dá bez problému proclít. Že si to koupí na sebe a nám to potom zcela legálně prodá. Takže jsme se s ním domluvili. A určitě to teda platili rodiče, protože na to bych určitě v té době neměl.</A>
        
            <Q speaker={RS}>Vy jste hodně mluvil o tom, že jste to ZX Spectrum používal hodně v práci a zejména na programování, protože vás to bavilo, ale používal jste ho vlastně i na něco jiného? Třeba na hraní videoher?</Q>
        
            <A speaker={ZV}>To jistě. Ona k tomu byla knížečka, kde byly nějaký prográmky. V tom ZX Spectru byl zadrátovaný <span class="c7 c3"><a class="c5" href="https://cs.wikipedia.org/wiki/BASIC">BASIC</a></span><span class="c2">, který jsme se na škole ale samozřejmě neučili. Takže já jsem šel podle těchto prográmků. Ty které mě zajímaly jsem si tam postupně nacpal. A v té době se dalo i ty hry vyměňovat. Pamatuju si třeba na nějakého kosmonauta, co tam lítá, nebo na sestřelování nějakých nepřátelských, potvor a nebo samozřejmě takový ten stolní tenis kde jsou ty dvě čárky. Takže jsem začal s těmihle prográmky. A protože se mi vždy líbily ty kondiciogramy, tak jsem si také začal dělat kondiciogramy – dokonce i s křivkami. U toho ZX Spectra byl samozřejmě problém, že v té době se k němu v podstatě nedala sehnat tiskárna. Já jsem potom myslím k tomu ZX Spectru někde sehnal dálnopis, který se dal ovládat zvuky. Takže se tam vlastně připojilo ZX Spectrum a z reproduktoru to pískalo a ten dálnopis psal.</span></A>
        
            <Q speaker={VS}>A ta příručka, kterou jste zmiňoval – ta byla v angličtině nebo v němčině?</Q>
        
            <A speaker={ZV}>V angličtině. </A>
        
            <Q speaker={VS}>Takže jazyková bariéra nebyla problém?</Q>
        
            <A speaker={ZV}>Jak už jsem říkal, jsem programátor který měl rád matematiku a fyziku a jazyky šly zcela mimo něj. Já nemám rád ta různá divná pravidla, které se tam objevují. Nicméně na angličtinu jsem chodil od druhé třídy základní školy, kde jsme měli takový anglický kroužek. Dělal to tehdy nějaký pan Kraus, který byl v druhé světové válce, někde v Africe s anglickým sborem. Po válce tady pak začal učit děti angličtinu. A i když učil moc hezky – kreslil obrázky, ptal se nás, jak se řekne anglicky jablko apod. – tak jsem se tu angličtinu, nikdy nenaučil. Nebo řeknu to takhle – mluvit neumím. Ve své podstatě ani nerozumím. Angličanovi rozhodně ne, pokud se budu bavit s někým jiným, třeba Japoncem, tak tomu asi rozumět budu. Nicméně číst jsem se naučil celkem bez problému. Zvláště pak ta technická angličtina, ta je úplně bezproblémová.</A>
        
            <Q speaker={RS}>Vy jste říkal, že jste se dostal k několika programům na ZX Spectrum. Jak jste se vlastně k těmto věcem dostával? </Q>
        
            <A speaker={ZV}>To jsme si nějakým způsobem měnili. Vím, že to někdy byl problém nahrát, protože v okamžiku, kdy se ten program nahrál do ZX Spectra, tak už to nešlo vyplivnout ven. Takže se to nahrávalo přes kazeťák, takže po druhé, třetí kopii už byl ten program nečitelný. </A>
        
            <Q speaker={VS}>A s kým jste si ty programy vyměňoval? S lidmi z vysoké školy? </Q>
        
            <A speaker={ZV}>Vzhledem k tomu, že jsme byli na ČVUT, tak jsem pak už nebyl jediný, kdo ten počítač měl, takže ano.</A>
        </Chapter>
        <Chapter title="Práce na ČVUT">
        
        
            <Q speaker={VS}>Jak jste se tehdy dostal k té pozici na ČVUT? A proč jste vlastně odešel?</Q>
        
            <A speaker={ZV}>Takhle – z ČVUT jsem byl odejit. Já tam pracoval jako asistent a jako asistent jsem měl smlouvu na tři roky. Pokud se asistent osvědčí, tak se smlouva s ním po třech letech prodlouží a stane se z něj odborný asistent. Nicméně já mám doopravdy určité problémy s lidmi, což zrovna u učitele není úplně ideální stav. On si toho později všimnul rektor ČVUT, který byl současně vedoucím naší katedry – nějaký profesor Klíma. Takže mi neprodloužil smlouvu. Za což jsem mu doopravdy vděčný, protože kdyby mě nevyhodil, tak bych tam byl pravděpodobně doteď. Pak jsem přišel na UUVPP (Ústřední ústav pro vzdělávání pedagogických pracovníků), což bylo velice podobné tomu, co jsem dělal na tom ČVUT – zase jsem učil. Pak jsem vystřídal další čtyři zaměstnání. Chvíli jsem pracoval jako programátor v České televizi, kde jsem ale vydržel asi dva měsíce. Pak jsem pracoval na Albertově na ČVUT, na Fakultě strojní, tam jsem vydržel měsíc. Postupně jsem prostě došel k tomu, že nejlepší je být OSVČ a nemít žádného nadřízeného.</A>
        
            <Q speaker={VS}>A během tohoto hledání zaměstnání jste spolupracoval s otcem na těch pořadech? </Q>
        
            <A speaker={ZV}>Ano. Tou dobou pořád ještě běžel <span class="c0">Videostop</span><span class="c3">. V té době už také musel běžet </span><span class="c0 c7"><a class="c5" href="https://www.csfd.cz/film/250792-kufr/prehled/">Kufr</a></span><span class="c2">. Takže jsem dělal tyto soutěže a věci pro redakci vzdělávání. Ono po posledním zaměstnání jsem si řekl, že zůstanu u těch zábavních pořadů, protože to mě fakt bavilo a bylo jasné, že to ještě nějakou dobu poběží. A i když bylo jasné, že Česká televize nebude platit moc, tak mě to na to co jsem potřeboval stačilo. Později samozřejmě přišla Nova, přišla Premiéra, posléze Prima a přišel Barrandov – to už jsem se pak nenudil.</span></A>
        </Chapter>
        <Chapter title="Začátky v ČST a Videostop">
        
        
            <A speaker={ZV}>No a teď se vrátím teda k té Československé televizi. První pořad, který jsem vlastně dělal, byla inscenace – konkrétně <span class="c3">nějaké sci-fi</span><span class="c2">. Hrál v tom, myslím, Radek Brzobohatý. Já jsem celý ten scénář nečetl, četl jsem jenom tu část, která mě zajímala, nicméně odehrávalo se to v jaderné elektrárně, která nějakým způsobem kolabovala, zvyšovala se tam radioaktivita a ten Radek Brzobohatý tam hrál nějakou dvojroli, kdy hrál jednak člověka a jednak androida, který tam měl být vyslán, aby tu elektrárnu nějakým způsobem zachránil. Podotýkám, že to bylo ještě před Černobylem – od Černobylu se už tahle hra už samozřejmě nehrála. Protože se celá ta inscenace odehrávala na velíně, tak tam byla spousta monitorů, na kterých z kazet běžely různé obrázky. Nicméně tam chtěli i monitor, na kterém je graf, kde se ukazuje ta zvyšující se radioaktivita. Což v té době byl problém. No a táta věděl, že mám to ZX Spectrum, tak navrhnul, že by se to dalo udělat s za pomocí něj. Takže během té inscenace jsem seděl za tou monitorovou stěnou, byl jsem připojený kabelem k monitoru, a vykresloval jsem tam ten graf, který se postupně zvyšoval. Byli s tím celkem spokojení, nebo si aspoň nikdo nestěžoval.</span></A>
        
            <Q speaker={RS}>A to běželo na tom vašem ZX Spectru?</Q>
        
            <A speaker={ZV}>Ano. Já jsem udělal program, u kterého když jsem zmáčkl tlačítko nahoru, tak ten graf začal růst a naopak když jsem zmáčkl tlačítko dolů, tak graf začal klesat. Zkrátka hrozná kravina. Nicméně, táta v té době seděl v kanceláři s Vladimírem Bezděkem, který tou dobou začal vymýšlet <span class="c0">Videostop</span><span class="c3"> a přemýšlelo se o tom, jak udělat závěr pořadu tak, aby byl divácky zajímavý. Bavil se o tom tehdy s tátou a protože byli kamarádi, tak oba věděli, že mám ten počítač, který by se dal k tomuto účelu využít. Jako první nápad bylo něco podobného, jako je závěrečný bankomat z </span><span class="c0">AZ-kvízu</span><span class="c3">. Prostě měla být obrazovka rozdělena do očíslovaných obdélníků po kterých měl běžet nějaký bod a kdyby soutěžící zmáčkl to tlačítko, tak by se objevilo, co vlastně vyhrál. Což bylo málo zajímavé z toho důvodu, že v té době nešlo udělat to, aby televizní divák viděl, jaká pole jsou jaká a soutěžící naopak ne. Zkrátka z toho počítače byl jeden výstup a přes to nejel vlak. Takže tahle varianta se nakonec, myslím si, ani neobjevila. Mám pocit, že se tato varianta ani neobjevila v prvních dílech. Pak přišel nápad, že by se udělala napodobenina strojů, jak je ten jednoruký bandita, u kterého se mění ty hruštičky, švestičky, třešničky apod. Tak jsem něco takového naprogramoval. Protože ZX Spectrum mělo akorát vyvedenou sběrnici, takže jsem si nechal v televizi u kamarádů, kteří tomu po hardwarové stránce velmi dobře rozuměli, udělat bastl, který se do toho ZX Spectra zasunul, do něj se pak strčilo tlačítko a už to jelo. Jediný problém toho </span><span class="c0">Videostopu</span><span class="c2"> byl v tom, že šlo o živé vysílání. Většina soutěží teď, co vidíte, tak jsou samozřejmě ze záznamu. Tehdy to bylo živé vysílání, což samozřejmě v případě toho ZX Spectra byl problém, protože nahrát do něj program z kazety trvalo tak kolem pěti minut. Kdyby mi ta hra v průběhu vysílání vypadla, tak se nebude čakat, až se zase nahraje. Takže tam byla i varianta, že kdyby se to rozbilo, tak Rosák před sebou měl tři hrací kostky, s kterými se mělo v případě poruchy házet. Jestli jste ten pořad někdy viděli, tak před tím plátnem zhruba seděl Honza Rosák a vedle něj po levý straně, z pohledu té kamery seděl pan Čáslavský. A my jsme seděli vlastně na tý straně toho pana Čáslavského v podstatě okamžitě za ním.</span></A>
        
            <Q speaker={VS}>Viděl jste vlastně taky, co z toho ZX Spectra šlo za obraz? Byl třeba ten videosignál nějak rozdělovaný?</Q>
        
            <A speaker={ZV}>Na to plátno se promítalo zezadu projektorem a protože jsme seděli za ním, tak jsme to v podstatě viděli odtamtud. Hodně ze šikma, ale viděli. To ten problém nebyl. V té době to nemohlo být dělaný tak, že člověk má jednu ovládací obrazovku a pak samotný výstup. Všechno se odehrávalo na té jedné obrazovce, takže si člověk musel pamatovat ta tlačítka, která mačkal, aby se to rozjelo, vynulovalo apod. Nakonec jsem to dělal tak, že na ten nejspodnější řádek jsem si tam malým písmem napsal nápovědu pro to, co mám mačkat. Proto abych nebyl mimo, když v tom živým vysílání nastane nějaký malér a začnou <span class="c3">týct</span><span class="c2"> nervy.</span></A>
        
            <Q speaker={RS}><span class="c2">Kdo vlastně vymýšlel ty herní koncepty, které jste pak měl za úkol programovat? Pan Bezděk s vaším tatínkem?</span></Q>
        
            <A speaker={ZV}><span class="c3">To se přiznám, nevím. Ono se to vše ke mně dostalo přes tátu, ale kdo to navrhnul, nebo kdo to vymyslel, to doopravdy nevím. Nicméně, to samotné natáčení probíhalo tak, že my jsme tam přišli někdy kolem oběda. Všechno jsme si nachystali, proběhla zkouška s komparzem. Byli tam jak komparzisté za soutěžící, tak komparzisté za ty VIPáky, aby se vyzkoušelo, jak ty lidi mohou reagovat na otázky, protože někdy ty otázky nebyly položeny úplně dobře nebo aby se vyzkoušelo, jestli tam není nějaký problém v tom záznamu. Pak tam přišel ten státní podnik, jehož zaměstnanci se účastnili toho daného dílu. Nevím, jak byly ty podniky vybírané, ale pravděpodobně si tu účast zaplatili. S nimi se udělala taková zkouška – položili se jim tři otázky z nějakého předcházejícího dílu, aby se jim ukázalo, jak se to dělá. Tam byl velký problém vždycky v tom, že tam seděli tři (na začátku čtyři) VIPáci a ti soutěžící se jich museli ptát. Problém byl v tom, že pokud z těch čtyř VIPáků byl jeden nějak zajímavější, tak samozřejmě všechny otázky směřovaly na něj. Takže právě při téhle zkoušce se těm soutěžícím vysvětlilo, že se musí ptát nějak spravedlivě aby se někdo necítil odstrčený. No a pak byla večeře, všechny jsme vyhodili a ti soutěžící si pak zkoušeli tu hru. Já jsem tam měl udělanou takovou smyčku, kdy v momentě, kdy to dojelo tak se to hned spustilo znovu, abych u toho nemusel pořád sedět. Pak byla ta večeře a po večeři jsme tam přišli a čekalo se na patřičný povel. Nejdříve se rozjely kreslené titulky, které dělali pro změnu kolegové na Atari. Když jsem mimojiné později dělal </span><span class="c0 c7"><a class="c5" href="https://www.csfd.cz/film/291978-barrandovsky-videostop/prehled/">Barrandovský Videostop</a></span><span class="c3">, tak mi před tím dali záznam s původním </span><span class="c0">Videostopem</span><span class="c2">. A můžu říct, že po těch X letech, co od toho uplynulo, už to člověku přišlo takový hrozně pomalý – kvůli tomu jak tam ty lidi chodí, jak se to tam vykresluje apod. To bylo šílený, no. V tý době to byl ale úžasný pořad. Aspoň na něj fakt rád vzpomínám.</span></A>
        
            <Q speaker={VS}>S kým vším jste na tom pořadu spolupracoval? Byl tady zmíněný teda pan Bezděk, pak pan Rosák a pan Čáslavský, ale interagoval jste i s dalšími?</Q>
        
            <A speaker={ZV}>V podstatě s nikým. Pro nás byla směrodatná vždy produkce, což, jestli si pamatuji, byl Otakar Svoboda. Nás v podstatě zajímala produkce a režisér. Myslím, že ten pořad začínal Pavel Vantuch. Pak se na tom vystřídal, myslím Paukert, taky si myslím, že tam byl Adam Rezek a taky Soukup, ale nejsem si jist. Vím, že Petr Soukup potom dělal <span class="c0">Barrandovský Videostop</span><span class="c3">. Mezitím byla ještě celá řada napodobenin </span><span class="c0">Videostopu</span><span class="c3">, který samozřejmě nesměli používat ten původní název. V podstatě se ale nic z toho nechytlo. Ten </span><span class="c0">Barrandovský Videostop</span><span class="c2"> se už samozřejmě nevysílal živě, ale normálně se natáčel. Musím říct, že když se ten pořad natáčel, tak to bylo úžasný – člověk se fakt zasmál. Jednou jsem se na to ale podíval v televizi a protože ten pořad má určitou stopáž, takže všechno nepodstatný, se musí vystříhat. A většinou se vystříhá to, co je vtipný. Takže nakonec zbyde dokonale udělaný pořad, ale ve srovnání s tím, co jsem viděl, je hrozně osekaný.</span></A>
        
            <Q speaker={RS}>Ten <span class="c0">Videostop</span><span class="c2"> běžel jenom na tom ZX Spectru?</span></Q>
        
            <A speaker={ZV}><span class="c0">Videostop</span><span class="c2"> běžel rozhodně jenom na ZX Spectru. Nebo takhle – byly tam dva počítače: byl tam můj počítač a já jsem dělal jenom tu závěrečnou hru a pak tam byli kolegové, kteří měli Atari a ti dělali takový ten přílet těch čísliček a zároveň dělali i úvodní a závěrečný titulky. Ono když máte televizní režii a připojíte se do ní, tak ten signál, kterým se do ní připojujete, musí být naprosto synchronní s těmi ostatními signály. To si v současný době dělá ta režie. Ne tedy každá, protože třeba televizní režie to nedělají. Ty posílají takzvaný referenční signál a ta karta, ze které jde ten signál do té režie, se na ten referenční signál chytne a posílá to tam přesně v té frekvenci, kterou vyžaduje ta režie. To ZX Spectrum samozřejmě neumělo. Atari to taky úplně neumělo, ale kolegové z televize si tam pořídili nebo půjčili synchronizer, do kterého posílali ten signál, který už mohla přijmout ta režie. </span></A>
        
            <Q speaker={RS}>Vzpomněl byste si, jak se jmenoval kolega, který pracoval právě s tím Atari? </Q>
        
            <A speaker={ZV}><span class="c2">Kohout se jmenoval, ale přiznám se, že si nevzpomenu na křestní. V té době dělal technika na záznamech, kde si vyzkoušeli, že s tím Atari se dokážou připojit.</span></A>
        
            <Q speaker={VS}>A tušíte, jestli to začali dělat až pro ten <span class="c0">Videostop</span><span class="c2"> nebo jestli se to Atari použilo třeba už i na dřívější programy? </span></Q>
        
            <A speaker={ZV}>Co já vím, tak pro <span class="c0">Videostop</span><span class="c3">. To bylo určitě to první. Ono v té době to teprve celé začínalo. Říkám, např. ta moje kalkulačka byla tehdy úplný výkřik techniky a to ZX Spectrum bylo ještě někde úplně jinde. </span></A>
        
            <Q speaker={VS}>Setkal jste se s nějakým ohlasem na ten samotný počítač a na to, co na něm běželo? Protože myslím, že třeba minimálně v nějakých raných dílech je to ZX Spectrum i vidět.</Q>
        
            <A speaker={ZV}>Musím říct, že by se o to někdo vysloveně zajímal, to ani ne. Takhle, vy žijete samozřejmě už v zcela v jiné době. V té době, pokud jste se o to vyloženě nezajímal, tak jste ani nevěděl, co takový počítač je.</A>
        
            <Q speaker={RS}>Jasně, ale jak vaši spolupracovníci nahlíželi na to, že tam teď mají nějakou technologii, který vlastně moc nerozumí a moc asi ani neví, co třeba dělá?</Q>
        
            <Q speaker={VS}>A kterou vlastně ani ta televize nijak nevlastnila, ani v případě takhle velkého pořadu.</Q>
        </Chapter>
        <Chapter title="Další pořady ČST a Amstrad">
        
        
            <A speaker={ZV}><span class="c2">Ono takhle, velký pořad – v té době se to zase tak dalece nebralo. Teprve od těch 90. let dál už se z toho dělali velké pořady. Byl to v podstatě normální pořad, kde jsme se všichni znali. Co už byl větší problém, tak nikoho ani nenapadla varianta, co dělat, když se to celé porouchá. Měly tam sice ty kostky, ale vždycky jednou za čas jsme je museli přimět k tomu, aby si to vůbec zkusili, aby potom během živého vysílání najednou všichni na sebe nezůstali koukat, když to nepojede. I když musím teda říct, že to ZX Spectrum bylo velice spolehlivé. Na rozdíl od pozdějších počítačů a modré smrti u Windows. U toho ZX Spectra byl jediný problém, který se bohužel i několikrát zopakoval, že tam byla membránová klávesnice která moc nevydržela. Takže už jsem sebou měl i náhradní klávesnici, která byla zastrčená z boku, takže pokud nefungovala, tak jsem ji vždycky vytrhnul, a zastrčil jsem novou. Jednou jsem kvůli tomu neodjel pořad. V Československé televizi se dělali pořady, kde se měli jet krauly, titulky apod., k čemuž normálně složil titulkovač. Problém byl v tom, že ten titulkovač neuměl všechno. Byl československé výroby, „made in Tesla Rožnov” a nebyl úplně spolehlivý. Třeba jsme dělali ještě před revolucí nebo v okolí revoluce kurz francouzštiny. Problém byl, že ten televizní titulkovač neuměl francouzské znaky. Takže jsem tam přišel a dělal jsem to s tím počítačem. Nicméně jednou jsem takhle neodjel závěrečný titulky jednoho pořadu, protože ať jsem mačkal, jak jsem mačkal, tak to zkrátka nereagovalo. </span></A>
        
            <Q speaker={RS}>A asi to bylo živý vysílání, takže to byl extra průšvih, co?</Q>
        
            <A speaker={ZV}><span class="c2">Bylo to živé vysílání, ale v té době se to tak nebralo. Teď už by to průšvih byl, ale v té době, to bylo každému celkem jedno. Místo titulků tam zkrátka zvukař zahrál gong, zatmělo se a bylo to. </span></A>
        
            <Q speaker={VS}><span class="c2">Vybavíte si ještě nějaký jiný pořady, kde se takhle to vaše ZX Spectrum využilo?</span></Q>
        
            <A speaker={ZV}>S tím ZX Spectrem jsem dělal všechny tyhle titulky. Třeba u <span class="c0 c7"><a class="c5" href="https://www.csfd.cz/film/311059-tkm/prehled/">Televizního klubu mladých</a></span><span class="c3">. To byl za socialismu večerní pořad, uváděl to, myslím, Vala, kromě jiných. Byla to taková show, povídalo se tam, zpívaly se písničky a byly tam i krauly atd. Takže tam jsem tohle dělal. Nicméně se ZX Spectrem jsem pak dělal i </span><span class="c0">Kufr</span><span class="c3">. Protože ale </span><span class="c0">Kufr</span><span class="c3"> běžel relativně dlouho, tak pak jsem přešel i na rozumnější techniku. Tam byly potom ty PC/XT, PC/AT, PC 286, 386 atd., ale k tomu jsem se dostal až po revoluci. Začínal jsem právě na tom ZX Spectru.</span></A>
        
            <Q speaker={VS}>Chodil jste do nějakých počítačových klubů? </Q>
        
            <A speaker={ZV}>Já nejsem zrovna společenský člověk, ale věděl jsem o tom. Já jsem po ZX Spectru měl ještě <span class="c7 c3"><a class="c5" href="https://cs.wikipedia.org/wiki/Amstrad_CPC">Amstrad</a></span><span class="c2"> s disketovou mechaniku. Myslím, že ty diskety se musely otáčet, protože byly jednostranný. Měl k tomu dokonce i svůj vlastní monitor. A právě s tím Amstradem jsem asi dvakrát nebo třikrát navštívil nějaký počítačový klub, který se scházel v technickým muzeu – a musím říct, že mě to nějak nezaujalo. No a pak nastala éra internetu a rázem byly tyto problémy pryč. Ze začátku se na tom internetu daly ty programy pro PC bez problémů najít a zkopírovat. To jde teda i teď, ale samozřejmě v okamžiku, když se tím člověk zabývá profesionálně a má ve smlouvě napsáno, že pokud by byl nějaký problém kvůli použití nelegálního softwaru, tak si to zaplatím sám. Teď už všechen software kupuji, ale byla doba, kdy jsem měl vyhlídnuté stránky, na kterých se dal zajímavý software stáhnout zdarma.</span></A>
        
            <Q speaker={RS}>Používal jste vlastně ten Amstrad i ve své práci? </Q>
        
            <A speaker={ZV}>S tím Amstradem jsem snad udělal jen jeden pořad. Obecně mě ten Amstrad oproti tomu ZX Spectru zklamal. Na druhou stranu, s tím Amstradem se dalo i tisknout, protože jsem k němu měl dokonce originální tiskárnu. Tohle už bylo v době, kdy jsem dělal asistent na vysoké škole, což už bylo někdy po roce 1985. A protože jsem vedl cvičení, tak abych si zjednodušil práci, tak jsem veškeré cvičební úkoly tisknul na cyklostyl každému zvlášť na tom Amstradu. Každý žák měl svoje data a já jsem pak měl list s výsledkama. Takže jsem jim to vždy rozdal a oni to nenáviděli a taky nenáviděli mě. </A>
        
            <Q speaker={VS}>Jak jste to ZX Spectrum používal ve volném čase? Začal se z něj stávat pracovní nástroj? A s jakým očekáváním jste si pořídil ten Amstrad?</Q>
        
            <A speaker={ZV}>Já jsem to ZX Spectrum vždycky bral ne jako pracovní nástroj, ale spíš jako hračku. Jednak samozřejmě kvůli těm hrám, které byly v té době úplně úžasné. To jsem si zval kamarády a hráli jsme si nějaký střílečky apod. Pracovní nástroj se z toho stal až v době <span class="c0">Videostopu</span><span class="c2">, nicméně i v té době jsem to používal zejména jako herní počítač. Ten Amstrad jsem si pak koupil, protože se mi nelíbilo to nahrávání z kazeťáku, i když je pravda, že k tomu ZX Spectru jsem sehnal i mechaniku na pět a čtvrtkový diskety. Ale pořád to nebylo ono. Mně se to nelíbilo, přišlo mi to už takový zastaralý. A ten Amstrad mi přišel, že by mohl být perfektní, protože měl tu disketovku a tiskárnou, takže by to mohl být zkrátka krok dál. A byl to krok dál, co se týče třeba té školy. Tam bych to asi na ZX Spectru neudělal. Nicméně pro práci v televizi jsem ten Amstrad použil snad jednou.</span></A>
        
            <Q speaker={VS}>Vzpomenete si na co?</Q>
        
            <A speaker={ZV}>My jsme tehdy dělali pro redakci vzdělávání takové vzdělávací pořady. Přiznám se, že už vůbec netuším, co to bylo. Typicky to byly pořady, kde někdo chytrý něco vykládal a měl se tam občas objevit graf, nějaký obrázek, nějaké schéma a tak dále. </A>
        
            <Q speaker={VS}>A u Amstradu byl stále ten problém s tou synchronizací, jako byl u toho ZX Spectra?</Q>
        
            <A speaker={ZV}>U toho Amstradu se to taky točilo z obrazovky počítače. Což znamená, že jsme šli do nějaké temné místnosti a kameru namířili na ten monitor od toho počítače.</A>
        
            <Q speaker={RS}>Tyhlety věci v této době většinou řešili interní animátoři, kteří animovali tyto věci ručně. Existuje nějaký důvod, proč se z ničeho nic začalo přecházet na ten počítač? Bylo to levnější případně rychlejší? </Q>
        
            <A speaker={ZV}>Levnější to bylo určitě. Já můžu říct, že za <span class="c0">Videostop</span><span class="c2"> jsem bral dvacet pět korun na hodinu. S tím, že ten jeden díl se točil tak deset hodin. Takže jsem si za ten jeden den vydělal dvě stě padesát korun.</span></A>
        
            <Q speaker={VS}>Jak jste se k tomu Amstradu dostal? </Q>
        
            <A speaker={ZV}>Určitě to bylo zase ze zahraničí, ale na rovinu se vám přiznám, že tím, jak jsem ho odsunul stranou, tak moc neuvědomuji, jak jsme ho tehdy sehnali. </A>
        </Chapter>
        <Chapter title="Práce v UUVPP">
        
        
            <Q speaker={VS}>A počítám, že jste s k němu dostal ještě před revolucí? </Q>
        
            <A speaker={ZV}>Jo, určitě. Stoprocentně to bylo před revolucí, protože když byla revoluce v roce 1989, tak to už jsem na škole, kde jsem ho používal, nebyl. Takže jsem se k němu dostal zhruba dva roky před revolucí. Když byla revoluce, tak to už jsem byl tady v Myslíkových v UUVPP, Ústředním ústavu pro vzdělávání pedagogických pracovníků. </A>
        
            <Q speaker={VS}>A co jste tam dělal?</Q>
        
            <A speaker={ZV}>Ústředně jsem vzdělával pedagogické pracovníky. Né… měli jsme tam takovou počítačovou místnost, o kterou jsem se víceméně staral a ve které byl jeden nebo dva počítače <span class="c7 c3"><a class="c5" href="https://cs.wikipedia.org/wiki/IQ_151">IQ 151</a></span><span class="c2">. A je fakt, že už tam bylo i nějaké PC/XT. </span></A>
        
            <Q speaker={VS}>A ty pedagogické pracovníky jste vzdělával v tom, jak pracovat s počítači?</Q>
        
            <A speaker={ZV}>My se tam hlavně snažili nepracovat. To byla taková doba. A mě to, musím říct ani moc nezaujalo. Ale ano, občas jsme si tam zvali ty pedagogické pracovníky, což byli učitelé základních škol, kteří se zabývali právě informatikou. My jsme tehdy měli i připravený na VHSce takový pořad, který jsme si sami vytvořili a kde jsme měli ukázky různých programů a počítačových her. K tomu jsme měli navíc takové krátké vystoupení, po kterém jsme je předali dalším kolegům, kteří je zase učili o něčem jiném. Takže ti učitelé tam strávili sice celý den, ale u nás byly asi hodinu.</A>
        
            <Q speaker={VS}>A co za programy jste ukazovali v tom pořadu?</Q>
        
            <A speaker={ZV}>Různé hry, které jsme tak různě popůjčovali nebo okopírovali a ukazovali jsme jim, jak se pracuje třeba s <span class="c0">T60</span><span class="c0 c7">2</span><span class="c2"> – jak se pracuje s textovým editorem. Nicméně jsme jim hlavně ukazovali, že to existuje a pokud by na školu dostali počítač, tak aby věděli, co mají chtít. Protože v té době samozřejmě ty počítače na školách nebyly. Já si pamatuji, že když jsem v roce 1988 odcházel z ČVUT, tak tam s velkou slávou otevřeli pracovnu s IQ 151. My jsme tam měli pracovnu, na každém stole bylo jedno IQ a na něm samozřejmě černobílý Merkur. </span></A>
        </Chapter>
        <Chapter title="Revoluce, Porevoluční změny, Komerční televize a Nástup PC">
        
        
            <Q speaker={RS}>Vy jste asi nějak prožil revoluci a zažil jste i jak se revoluční změny projevují na Československé a později na České televizi. Byl byste schopen o tom něco povědět? </Q>
        
            <A speaker={ZV}>To, jak se změny projevily v Československé televizi jsem moc nezaznamenal, protože já jsem si tam zkrátka dělal jenom to svoje. To znamená, že jsem tam přišel, postavil si počítač, odjel jsem pořad a šel jsem domů. Posléze se teda napsala faktura a dostal jsem zaplaceno, což musím tedy říct, že na rozdíl od některých jiných televizí, v tomto ohledu u České televize nikdy nebyl problém. Ale co se týče těch změn, tak to vám toho moc nepovím. Samozřejmě vyhodili vedení, místo kterého tam přišlo jiné vedení, které se několikrát vystřídalo.</A>
        
            <Q speaker={RS}>A měly třeba ty pořady, na kterých jste dělali nějakou přestávku? Upravovaly se nějak? </Q>
        
            <Q speaker={VS}>Nějaké dopady na vaší práci tam nebyly? </Q>
        
            <A speaker={ZV}>Ne, to určitě ne. Vlastně to přerušení toho <span class="c0">Videostopu</span><span class="c3">, bylo ještě dlouho před revolucí. Místo toho byl vysílaný ten úžasný roční pořad o Sovětském svazu. Nicméně revoluce se na </span><span class="c0">Videostopu</span><span class="c2"> nijak nepodepsala. I lidi, se kterýma jsem pracoval, zůstali stejný, protože ti nikdy nebyli na tak vysokém místě, aby je změna režimu nějakým způsobem ovlivnila. Samozřejmě jsem některé ty změny pocítil, protože po revoluci samozřejmě nastalo období značné inflace, takže i cena mé práce se postupně zvyšovala. Vždy jsme se domluvili, kolik se přihodí na tenhle půlrok a kolik se přihodí na další půlrok. Pak samozřejmě přišly další pořady a více se to rozjelo. Protože tam přišli i externí pracovníci a často přišli s dalšími nápady. Ty devadesátky byly takové období, který se mně teda hrozně líbilo, protože tam si člověk připadal, že to bylo to, kvůli čemu byl na tom Václaváku. Pak to šlo do prdele, ale to je jiná věc. A jak jsem já prožil revoluci? Když už bylo jasné, že na Václavák nepřijedou ani kropící vozy, ani žádné tanky, tak jsme tam samozřejmě s kolegama z UUVPP šli. Byli jsme tam dvakrát, možná třikrát. Už teda ke konci, kdy už bylo jasné, že se nemůže nic stát. Takže pro mě to proběhlo úplně bez problémů. A hrozně mě v té době nadchlo. V té době.</span></A>
        
            <Q speaker={VS}>Jak vlastně vaše okolí nahlíželo nato, že chcete být OSVČ? Protože to byl pojem, který samozřejmě předtím neexistoval. </Q>
        
            <A speaker={ZV}>Onon když jsem začal dělat ten <span class="c0">Videostop</span><span class="c2">, tak jsem byl zaměstnaný v Československé televizi na VPP – Vedlejší pracovní poměr. Měl jsem na to smlouvu a pracoval jsem. Takže ten přechod na OSVČ nebyla taková změna – jen jsem místo vedlejšího pracovního poměru měl živnostenský list. Předtím jsem také fakturoval, takže v tomto ohledu se vůbec nic nezměnilo. Je fakt, že jsem trošinku obavy v okamžiku, kdy jsem se rozhodl, že už se nenechám zaměstnat. Pak jsem si tedy řekl, že je to asi dobrý nápad, i když táta naopak tvrdil, že to dobrý nápad není. Ale prosadil jsem si to. Koneckonců, v té době už mě bylo hodně přes dvacet. Protože, jak říkám, mě nadřízený vždycky dost štvali. Tady sice mám nad sebou nějaké nadřízené, ať už je to režisér, produkce, dramaturg, ale musím říct, že třeba v té Nově víceméně od začátku pracuju s lidma, který jsem tam poznal, se kterými se znám už dlouho. Jsem s nima kamarád, oni vědí, jaký já mám zvláštnosti a svým způsobem se jim přizpůsobují, za což jsem jim samozřejmě moc vděčný. No a já zase pro změnu vím, co potřebují oni.</span></A>
        
            <Q speaker={RS}>Lišila se něčím práce pro veřejnoprávní televizi a pro ty televize komerční?</Q>
        
            <A speaker={ZV}>Já si myslím, že zas tak zásadně ne. Z počátku bylo trochu nepřátelství mezi těmi televizemi. A my jsme to řešili velice jednoduše tím, že jsme se nenechávali psát do titulků. V tom okamžiku pak nikomu nevadilo, že děláme pro víc televizí naráz. Trochu problém jsem měl kvůli adventním koncertům – teď už to běží trochu jinak, ale tehdy tam zase seděly ty telefonistky, které přijímaly dary. Měly před sebou vždy notebook do kterého pak třeba psali že ,,pan Jan Novák z Pelhřimova dal 200 Kč.” Mně se to pak objevilo na počítači a já to pak poslal do té lištičky která byla dole na obrazovce. No a při těchto adventních koncertech se tam dělal právě záběr i na ty telefonistky a na mě, jak tam sedím a zaujatě koukám do počítače. Toto viděla nějaká vedoucí pracovnice z Novy která na mne vznesla požadavek, že pokud mám dělat pro Českou televizi, tak ať se aspoň neobjevuji na obrazovce. Jinak žádný problémy jsem neměl mezi jednotlivými televizemi. Koneckonců všichni ty lidi, do těch soukromých televizí vlastně přešli z České televize. Takže oni věděli, že já dělám tyhle soutěže. Takže když potom hledali někoho, kdo udělá nějakou soutěž, tak se většinou obrátili na mě. Jinými slovy, v podstatě všechny soutěže jsem dělal já. Pro víceméně všechny televize tehdy.</A>
        
            <Q speaker={VS}>Ještě poslední otázka k té přechodové éře – mohl byste povědět o tom, jak jste vnímal příchod PC-ček, jak jste interagoval třeba s BBS-kama apod.</Q>
        
            <A speaker={ZV}>To bylo samozřejmě naprosto úžasné v té době. Teď už to tak nebývá, ale bývaly různé výstavy výpočetní techniky, např. <span class="c7 c3"><a class="c5" href="https://cs.wikipedia.org/wiki/Invex">INVEX</a></span><span class="c3">, které se mi hrozně líbily. Já jsem všechny ty výstavy objížděl, a díval se, co je možné a co ne a hledal jsem způsob, jak si vybrat co nejvhodnější techniku pro tuhle práci. Což v té době byl trošinku problém, ale podařilo se mě to. Začínal jsem myslím u </span><span class="c7 c3"><a class="c5" href="https://cs.wikipedia.org/wiki/Intel_80386">386</a></span><span class="c3">, zvukovou kartu jsem používal nějaký Sound Blaster. V té době se připojení počítače do toho televizního videořetězce dělalo takovou krabičkou, která převáděla VGA signál na SD signál a která se už dala i přímo sesynchronizovat tím, že ji byla poslaná reference a já jim dal přesně ten signál, který oni potřebovali. Problém samozřejmě byl, že se musely všechny ty animace a pohyblivé věci na obrazovce dělat pokud možno padesát snímků, aby se to necukalo, nerozjíždělo a podobně. Později se už dali sehnat i karty, které byly přímo připojené do té režie a které se i samostatně programovaly. Ono VGA výstup už používám na jiné věci než jsem používal dříve. Dám příklad – teď děláme pořad </span><span class="c0 c7"><a class="c5" href="https://www.csfd.cz/film/1064208-na-lovu/prehled/">Na lovu</a></span><span class="c2">, kde moderátor má monitor s těmi otázkami a odpověďmi, který má jako výstup právě VGA. A to, co vidíte na televizní obrazovce, to znamená ta lišta dole a ta časomíra a tak dále, tak to posílám právě z té speciální karty přímo do přenosového vozu, kde se to natáčí.</span></A>
        
            <Q speaker={VS}>Vy jste zmínil, že jste hodně hrál videohry na ZX Spectru a že to byla velká součást toho zážitku. Zůstalo to s vámi i na tom PC-čku?</Q>
        
            <Q speaker={RS}>Nebo i na tom Amstradu.</Q>
        
            <A speaker={ZV}>Jak jsem říkal, ten Amstrad šel úplně mimo. Tam jsem nesehnal moc lidí, kteří by ho měli, takže získat nějaké programy bylo velmi problematické. Na tom ZX Spectru jsem měl nesrovnatelně více her, než na tom Amstradu. Samozřejmě v okamžiku, kdy jsem měl PC, tak jsem tam samozřejmě hrál hry. A teď nepočítám takové ty pitomosti, jako je <span class="c0">Solitaire</span><span class="c3">, ale třeba </span><span class="c0">DOOM</span><span class="c3"> a jiné střílečky z prvního pohledu. Mně se tedy z toho dělalo vždy po půl hodině blbě. Potom jsem hrál různé skákací hry. V současné době hraju jednu hru pořád dokola – nějaké opice, co střílejí po balonkách, který takhle jdou po cestičkách. Přiznám se, ne že by mě hry nebavily, ale čím je člověk starší, tím je samozřejmě pomalejší, takže nějaké hry vyžadující postřeh, už jdou zcela mimo mě. A jak říkám, třeba u toho </span><span class="c0">DOOM</span><span class="c2"> se mi dělalo fakt blbě.</span></A>
        </Chapter>
        <Chapter title="Porevoluční televizní tvorba">
        
        
            <Q speaker={VS}>Zapojoval jste se později u těch herních show i do nějakého toho procesu návrhů herních praktik?</Q>
        
            <A speaker={ZV}>Pravidla hry jsem nikdy nenavrhoval a nikdy jsem se do toho ani necpal. Co chtěli, to jsem jim udělal. Na začátku jsem dělal tedy i grafiku, která byla často velmi jednoduchá grafika – byly tam nějaké otázky, které vyjížděly a tak dále. Tu grafiku jsem dělal zejména pro Československou, později teda tu Českou televizi, ale v okamžiku kdy začala vysílat Nova, tak ti už měli nějakou grafickou představu o tom, jak to má vypadat. Měli grafické oddělení, takže když jsem začal dělat nějaké ty jejich soutěže – <span class="c0 c7"><a class="c5" href="https://www.csfd.cz/film/250660-riskuj/prehled/">Riskuj!</a></span><span class="c3">, </span><span class="c0 c7"><a class="c5" href="https://www.csfd.cz/film/250659-chcete-byt-milionarem/prehled/">Chcete být milionářem?</a></span><span class="c3"> apod. – tak tam už si grafiku dodávali. Já jsem díky tomu zjistil, že je výrazně jednodušší, když tu grafiku dostanu a nikdo na mě neječí, co jsem to udělal za nesmysly. Od té doby to vlastně vyžaduji od všech televizí. Zároveň, když se začaly vysílat licencované pořady, jako je </span><span class="c0">Chcete být milionářem?</span><span class="c3">, </span><span class="c0 c7"><a class="c5" href="https://www.csfd.cz/film/254136-nejslabsi-mate-padaka/prehled/">Nejslabší! Máte padáka!</a></span><span class="c3">, </span><span class="c0 c7"><a class="c5" href="https://www.csfd.cz/film/643439-1-proti-vsem/prehled/">1 proti všem</a></span><span class="c3"> apod., tak tam ta grafika byla dána samotnou licencí, kde bylo řečeno, jak to má vypadat. Na Nově jsem se mimojiné podílel na jejich úplně pvním odvysílaným pořadu, což byl přenos z muzea na Václaváku, kde televizní diváci rozhodovali, který pořad jako první půjde na televizi Nova. Nakonec vybrali </span><span class="c0 c7"><a class="c5" href="https://www.filmovyprehled.cz/cs/film/397700/obecna-skola">Obecnou školu</a></span><span class="c3">. Bylo to děláno mimojiné tak, že tam byly telefonistky, kterým volali diváci a já jsem tam měl počítač a zaznamenával jsem ty odpovědi. Pak tam vyjížděly sloupečky a na závěr se ukázalo, že to vyhrála ta </span><span class="c0">Obecná škola</span><span class="c2">.</span></A>
        
            <Q speaker={VS}>Implementoval jste si ty hry z těch show vždy sám, nebo jste dostával nějaký předpřipravený program?</Q>
        
            <A speaker={ZV}>Vždy jsem si je implementoval sám. Třeba u <span class="c0">Chcete být milionářem?</span><span class="c2"> a u těch ostatních licencovaných her, ti kteří tu hru prodávali, nabízeli i software, s tím, že ten software běží na dost specifickém hardwaru, takže to často nabízeli i s hardwarem. Cenově se to pohybovalo ale úplně jinde, než jsem se pohyboval já. Navíc, když dostanete program nějaký hotový software, tak do něj v životě nezasáhnete. I kdybyste ho dostali se zdrojovým kódem, tak není šance do toho nějak rozumně zasáhnout. Naopak když jsem ty programy dělal sám, tak jsem přesně věděl, co jsem kde udělal. A když bylo třeba něco upravit, tak jsem věděl, kam šáhnout. A samozřejmě ta produkce ví, že když se něco podělá, tak že já to opravím a že já jsem za to zodpovědný. Kdyby tam byl nějaký cizí počítač a ten odešel, tak s tím bych nic neudělal. </span></A>
        
            <Q speaker={RS}>A to co říkáte platí i pro práci na těch současných licencovaných pořadech? Jako <span class="c0">Na lovu</span><span class="c2">?</span></Q>
        
            <A speaker={ZV}>U <span class="c0">Na lovu</span><span class="c3"> myslím nabízeli software, ale kecal bych. Mě už tyhle informace ani neříkají, protože vědí, že si to budu dělat stejně sám. A je to zcela logický – třeba ten </span><span class="c0">Chcete být milionářem?</span><span class="c3"> byla první velká soutěž, která se tady dělala. Do té doby mi na všechny soutěže stačil jeden počítač. Na </span><span class="c0">Chcete být milionářem?</span><span class="c3"> už jsem měl dva počítače, pak nějaký notebooky atd. To už byla doopravdy velká soutěž. U toho </span><span class="c0">Na lovu</span><span class="c2">, tak tam mám taky několik počítačů a notebooků, pak tam řídím světla, jsou tam ta tlačítka, zvuky a další věci, které tam vidíte. Kdybych tohle dostal jako od někoho udělaný a něco bylo potřeba změnit, tak není šance.</span></A>
        
            <Q speaker={VS}>Před rozhovorem jste říkal, že děláte na <span class="c0 c7"><a class="c5" href="https://www.csfd.cz/film/251049-az-kviz/prehled/">AZ-kvízu</a></span><span class="c2">, ale že jste na něm nezačínal.</span></Q>
        
            <A speaker={ZV}><span class="c0">AZ-kvíz</span><span class="c2"> původně dělala nějaká firma AKI, jestli se nepletu. Oni se zaměřovali spíše na grafiku pro sportovní přenosy. Ale přiznám se, že ani nevím, co se tam tehdy po těch deseti letech, co to dělali, vlastně stalo. Nicméně v jeden moment se změnil celý štáb, kromě střihače a jedné asistentky. Takže jsem tam přišel já a přišel tam nový režisér.</span></A>
        
            <Q speaker={RS}>Když jste přebíral ten <span class="c0">AZ-kvíz</span><span class="c2">, tak jste si ten software k tomu kompletně udělal odznova?</span></Q>
        
            <A speaker={ZV}>Ano. Ono aby ta změna byla nějak vysvětlená, tak se změnila i dekorace, grafika apod. Takže ano, ten software jsem pro ten <span class="c0">AZ-kvíz</span><span class="c2"> dělal sám. Zase jsem tu grafiku dostal od nějaké firmy z Prahy, už si ani nevzpomenu, jak se jmenovala.</span></A>
        
            <Q speaker={VS}>Ty pořady se točily živě, primárně během té Československé televize a pak už se později všechno, jelo ze záznamu?</Q>
        
            <A speaker={ZV}><span class="c0">Videostop</span><span class="c3"> se jel živě, ale to byla dost výjimka. Většina soutěží se jela ze záznamu. Nicméně, po revoluci jsem dělal i živá vysílání, jako třeba </span><span class="c0">Miss České republiky</span><span class="c3">, </span><span class="c0">Zlatého slavíka</span><span class="c3"> apod. A pak jsem dělal i na pořadu, který byl vysílaný, nevím jestli ještě na Premiéře nebo už na Primě. Vysílalo se to z Paláce kultury a tady na Vyšehradě. Oni tam měli vysílací pracoviště a studio. A my jsme tam dělali nějakou soutěž. Jednu dobu to uváděla i Heidi Janků. Přiznám se, že nevím, jak se to jmenovalo. Ale běželo to několik let. A protože to bylo celé živě a zároveň šlo o denní soutěž, tak každý den jsem tam musel přijet, pokusit se někde zaparkovat, což bylo šílený problém a pak to celé odjet. Ale to byla fakt výjimka. Většina těch pořadů, který jsem dělal – nepočítaje ty velké živé přenosy, jako byl </span><span class="c0">Zlatý slavík</span><span class="c3"> – se jely ze záznamu. Nedovedu si představit, jak bychom </span><span class="c0">Na lovu</span><span class="c2"> dělali živě.</span></A>
        
            <Q speaker={VS}>Vzhledem k tomu, že jste si vše psal sám, tak jaké bylo vaše technické zázemí? Na jaký hardware jste to později dělal? V jakém jazyku jste to psal?</Q>
        
            <A speaker={ZV}>V současné době všechny pořady, které dělám, dělám na Windows XP a dělám je ve Visual Basicu. Na PC jsem ale začínal s programovacím jazykem Pascal. To bylo ještě na 386 nebo 486. On Pascal byl v té době snad jediný programovací jazyk, který se mi hodil. To byla ještě ta doba, kdy jsem měl výstup přímo z VGA karty, která šla do nějakého převodníku a z toho převodníku to potom šlo do televizního řetězce s kterým byl ten převodník synchronizován. Později jsem přešel na ty speciální karty, které jsou programovatelné a jsou přímo připojitelné do toho televizního řetězce. V té době jsem začal programovat v tom Visual Basicu nebo Visual Studiu. A v té době jsem zůstal i u těch Windows XP, který mi teda vyhovují hlavně v tom, že nemají pořád snahu se aktualizovat. Ony už ani nemůžou, naštěstí. Teď jak dělám třeba to <span class="c0">Na lovu</span><span class="c2">, tak si nedokážu moc představit, co bych dělal, kdyby se mi tam uprostřed natáčení objevilo, že se ten systém chce aktualizovat a ať mu to povolím.</span></A>
        
            <Q speaker={VS}>Takže od nějakého toho přelomu milénia celou dobu fungujete takto?</Q>
        
            <A speaker={ZV}>No, tou dobou tam byly Windows Millenium, nebo Windows 2000. Na počítači na kterém jsem programoval jsem pak kompletně přeskočil Visty, ty byly nepoužitelný a teď programuju na Windows 11.</A>
        
            <Q speaker={RS}>Jak se na tu vaši práci nahlíželo a dnes nahlíží vlastně právně? Ve smyslu komu třeba patří ty vaše programy? A jak moc to ty lidi vůbec řeší a jak se to řešilo právě třeba v těch 80. letech?</Q>
        
            <A speaker={ZV}>V 80. letech se to samozřejmě neřešilo vůbec. Ono se to do značné míry neřešilo ani začátkem těch 90. let a začalo se to řešit až s nástupem komerčních televizí. V těch 80. letech jsem měl u toho <span class="c0">Videostopu</span><span class="c3"> objednávku, kde bylo řečený, kolik dostanu na hodinu, v kolik moje práce začíná a končí a že mám přijít včas. Teď když mám smlouvu, ať už na ten </span><span class="c0">AZ-kvíz</span><span class="c3"> nebo smlouvu k </span><span class="c0">Na lovu</span><span class="c3">, tak je ta smlouva daleko delší. Zvlášť Česká televize se v tom vyžívá. Já mám pro </span><span class="c0">AZ-kvíz</span><span class="c2"> smlouvu vždy na půl roku, která je na nějakých osm listů popsaných z obou stran drobným písmem. V té smlouvě jsou samozřejmě rozepsané ty pořady, na kterých mám dělat, ale pak je tam teda i to, co můžu, co nemůžu apod. Musím se přiznat, že jsem to nikdy ani nějak podrobně nečetl. Jednou jsem se do toho začetl a zjistil jsem, že mám nárok na sekretářku, auto a telefon, když dokážu zdůvodnit, proč to potřebuju. Naopak u Novy ty smlouvy čtu. Jako čtu je dost podrobně, protože tam ta smlouva má nějakých šest stran z obou stran. Ono je tam dost podrobně napsáno, co můžu, co nemůžu a co se stane, když udělám něco, co nemůžu. A kolik mě to bude stát. Proto v případě Novy nemůžu zajít úplně do detailů. </span></A>
        
            <Q speaker={VS}>Ale ten herní program, který si sám píšete, tak je vaše dílo a vy jim jen nabízíte licenci? </Q>
        
            <A speaker={ZV}>Prodávám jim výhradní licenci. To znamená, že ten software je v podstatě můj, ale oni na něj mají veškerý práva a já ho nesmím prodat někomu dalšímu. </A>
        
            <Q speaker={RS}>A takhle to probíhalo už někde od těch 90. let? </Q>
        
            <A speaker={ZV}>Ono se to postupně vyvíjelo a teď už to teda je doopravdy vychytané. Evidentně po jejich zkušenostech už to mají vychytané tak, že je to, v podstatě neprůstřelný. A že kdyby chtěli, tak mě po každém natáčení jsou schopni zkásnout o padesát tisíc.</A>
        
            <Q speaker={RS}>Než ukončíme rozhovor, napadá vás takhle z hlavy ještě něco zajímavého ohledně vaší činosti? </Q>
        
            <A speaker={ZV}>Mně toho zajímavého přijde samozřejmě hodně, ale na druhou stranu už si taky nic nepamatuju. Dělal jsem těch pořadů doopravdy šílený množství – některé mi v hlavě utkvěly, některé naopak vůbec. Hrozně rád vzpomínám třeba na pořad <span class="c0 c7"><a class="c5" href="https://www.csfd.cz/film/250790-o-poklad-anezky-ceske/prehled/">O poklad Anežky České</a></span><span class="c2">. To byl úžasný pořad. Jeden díl se točil dva dny. Byli jsme vždy na tom hradě, ten jsme si prolezli, mohli jsme samozřejmě tam, kam ostatní nemohli. Nejhorší na tom bylo, že v té době notebooky apod., tolik nebyly, takže táhnout ten počítáč s velkým monitorem a CRTčkem a se spoustou dalších kabelů do hradní věže, byla občas chuťovka. </span></A>
        
            <Q speaker={RS}>Tak tím pádem moc děkuji za rozhovor a já ho ukončuji.</Q>
        </Chapter>
        
        

        <center>
            <i>Konec rozhovoru</i>
        </center>
        
        
        
    </div>
</Interview>